USE nox_hours;

CREATE EVENT delete_old_reports
ON SCHEDULE EVERY 24 HOUR
ON COMPLETION PRESERVE
DO
    DELETE FROM reports WHERE CURRENT_TIMESTAMP > DATE_ADD(created, INTERVAL 90 DAY );

CREATE EVENT delete_old_activities
ON SCHEDULE EVERY 24 HOUR
ON COMPLETION PRESERVE
DO
    DELETE FROM activities WHERE CURRENT_TIMESTAMP > DATE_ADD(created, INTERVAL 30 DAY);